/**
 * Authentic Sharma Kirana Store Seed Dataset
 */
exports.storeProfileData = {
  storeName: 'Sharma Kirana Store',
  tagline: 'Quality Provisions & Daily Groceries',
  ownerName: 'Ravi Sharma',
  phone: '+91 98490 23145',
  email: 'ravi.sharma@kiranaos.in',
  gstin: '36AABCS1429B1Z8',
  address: 'Shop #4, Near Hanuman Temple, KPHB Phase 3, Hyderabad, Telangana - 500072',
  upiId: 'sharmakirana@icici',
  operatingHours: '07:00 AM - 10:30 PM',
  currencySymbol: '₹',
  posStatus: 'Online • Synced'
};

exports.productsData = [
  {
    id: 'PROD-001',
    name: 'Sona Masoori Raw Rice (25kg Bag)',
    sku: 'RIC-SONA-25K',
    category: 'Grains & Rice',
    purchasePrice: 1250,
    sellingPrice: 1350,
    stock: 18,
    minStock: 30,
    unit: 'bags',
    supplierId: 'SUP-001',
    supplierName: 'ABC Distributors',
    velocityDaily: 9.3,
    status: 'low',
    trend: '+21% this week'
  },
  {
    id: 'PROD-002',
    name: 'Aashirvaad Shudh Chakki Atta (10kg)',
    sku: 'ATT-AASH-10K',
    category: 'Flours & Atta',
    purchasePrice: 410,
    sellingPrice: 465,
    stock: 24,
    minStock: 20,
    unit: 'bags',
    supplierId: 'SUP-002',
    supplierName: 'Balaji Trading Co',
    velocityDaily: 4.8,
    status: 'healthy',
    trend: '+8.4%'
  },
  {
    id: 'PROD-003',
    name: 'Fortune Sunlite Sunflower Oil (1L Pouch)',
    sku: 'OIL-FORT-1L',
    category: 'Edible Oils',
    purchasePrice: 128,
    sellingPrice: 145,
    stock: 4,
    minStock: 25,
    unit: 'pouches',
    supplierId: 'SUP-002',
    supplierName: 'Balaji Trading Co',
    velocityDaily: 8.5,
    status: 'low',
    trend: '+18% demand'
  },
  {
    id: 'PROD-004',
    name: 'Tata Salt Vacuum Evaporated (1kg)',
    sku: 'SLT-TATA-1K',
    category: 'Salt & Sugar',
    purchasePrice: 22,
    sellingPrice: 28,
    stock: 8,
    minStock: 35,
    unit: 'packets',
    supplierId: 'SUP-003',
    supplierName: 'Sri Lakshmi Wholesalers',
    velocityDaily: 11.2,
    status: 'low',
    trend: '+15.2%'
  },
  {
    id: 'PROD-005',
    name: 'Toor Dal Premium Desi (1kg)',
    sku: 'DAL-TOOR-1K',
    category: 'Pulses & Dal',
    purchasePrice: 148,
    sellingPrice: 172,
    stock: 22,
    minStock: 20,
    unit: 'kg',
    supplierId: 'SUP-003',
    supplierName: 'Sri Lakshmi Wholesalers',
    velocityDaily: 6.1,
    status: 'healthy',
    trend: '+4.2%'
  },
  {
    id: 'PROD-006',
    name: 'Maggi 2-Minute Masala Noodles (70g)',
    sku: 'NDL-MAGG-70G',
    category: 'Packaged Food',
    purchasePrice: 12,
    sellingPrice: 14,
    stock: 0,
    minStock: 50,
    unit: 'packs',
    supplierId: 'SUP-005',
    supplierName: 'Nestlé Local Agency',
    velocityDaily: 18.0,
    status: 'out',
    trend: 'Stockout alert'
  },
  {
    id: 'PROD-007',
    name: 'Amul Taaza Homogenised Toned Milk (1L)',
    sku: 'MLK-AMUL-1L',
    category: 'Dairy',
    purchasePrice: 66,
    sellingPrice: 74,
    stock: 14,
    minStock: 20,
    unit: 'cartons',
    supplierId: 'SUP-004',
    supplierName: 'Amul Co-op Depot',
    velocityDaily: 14.5,
    status: 'low',
    trend: 'Daily perishable'
  },
  {
    id: 'PROD-008',
    name: 'Amul Butter Pasteurized (500g)',
    sku: 'BTR-AMUL-500',
    category: 'Dairy',
    purchasePrice: 245,
    sellingPrice: 275,
    stock: 15,
    minStock: 12,
    unit: 'packs',
    supplierId: 'SUP-004',
    supplierName: 'Amul Co-op Depot',
    velocityDaily: 3.2,
    status: 'healthy',
    trend: 'Stable'
  },
  {
    id: 'PROD-009',
    name: 'Dettol Original Bathing Soap (125g x 3)',
    sku: 'SOP-DETT-3PK',
    category: 'Personal Care',
    purchasePrice: 152,
    sellingPrice: 180,
    stock: 5,
    minStock: 15,
    unit: 'multipacks',
    supplierId: 'SUP-006',
    supplierName: 'HUL & Reckitt Agency',
    velocityDaily: 2.8,
    status: 'low',
    trend: 'Weekly steady'
  },
  {
    id: 'PROD-010',
    name: 'Surf Excel Quick Wash Detergent Powder (1kg)',
    sku: 'DET-SURF-1K',
    category: 'Home Care',
    purchasePrice: 178,
    sellingPrice: 210,
    stock: 19,
    minStock: 15,
    unit: 'packs',
    supplierId: 'SUP-006',
    supplierName: 'HUL & Reckitt Agency',
    velocityDaily: 3.5,
    status: 'healthy',
    trend: '+6.0%'
  },
  {
    id: 'PROD-011',
    name: 'Taj Mahal Tea Leaves (500g)',
    sku: 'TEA-TAJM-500',
    category: 'Beverages',
    purchasePrice: 310,
    sellingPrice: 360,
    stock: 12,
    minStock: 10,
    unit: 'boxes',
    supplierId: 'SUP-006',
    supplierName: 'HUL & Reckitt Agency',
    velocityDaily: 1.8,
    status: 'healthy',
    trend: 'High margin'
  },
  {
    id: 'PROD-012',
    name: 'Parle-G Glucose Biscuits (800g Family Pack)',
    sku: 'BSC-PARL-800',
    category: 'Snacks & Bakery',
    purchasePrice: 72,
    sellingPrice: 85,
    stock: 32,
    minStock: 25,
    unit: 'packs',
    supplierId: 'SUP-005',
    supplierName: 'Britannia & Parle Depot',
    velocityDaily: 7.2,
    status: 'healthy',
    trend: 'Consistent'
  },
  {
    id: 'PROD-013',
    name: 'Vim Dishwash Bar (300g)',
    sku: 'CLN-VIM-300G',
    category: 'Home Care',
    purchasePrice: 25,
    sellingPrice: 32,
    stock: 3,
    minStock: 25,
    unit: 'bars',
    supplierId: 'SUP-006',
    supplierName: 'HUL & Reckitt Agency',
    velocityDaily: 8.0,
    status: 'low',
    trend: 'Needs restock'
  },
  {
    id: 'PROD-014',
    name: 'Everest Royal Garam Masala (100g)',
    sku: 'SPC-EVER-100',
    category: 'Salt & Spices',
    purchasePrice: 78,
    sellingPrice: 94,
    stock: 2,
    minStock: 15,
    unit: 'boxes',
    supplierId: 'SUP-003',
    supplierName: 'Sri Lakshmi Wholesalers',
    velocityDaily: 2.1,
    status: 'low',
    trend: 'Festival demand'
  },
  {
    id: 'PROD-015',
    name: 'Moong Dal Dhuli (1kg)',
    sku: 'DAL-MOON-1K',
    category: 'Pulses & Dal',
    purchasePrice: 128,
    sellingPrice: 150,
    stock: 16,
    minStock: 15,
    unit: 'kg',
    supplierId: 'SUP-003',
    supplierName: 'Sri Lakshmi Wholesalers',
    velocityDaily: 3.4,
    status: 'healthy',
    trend: 'Stable'
  }
];

exports.suppliersData = [
  {
    id: 'SUP-001',
    name: 'ABC Distributors',
    category: 'Grains, Rice & Bulk Staples',
    contactPerson: 'Mahesh Agarwal',
    phone: '+91 94401 88231',
    email: 'orders@abcdistributors.in',
    pendingOrders: 0,
    totalPurchased: 248000,
    lastOrderDate: '18 Oct 2024',
    status: 'Active'
  },
  {
    id: 'SUP-002',
    name: 'Balaji Trading Co',
    category: 'Edible Oils, Ghee & Atta',
    contactPerson: 'K. Balakrishna',
    phone: '+91 98480 11942',
    email: 'balaji.traders.hyd@gmail.com',
    pendingOrders: 1,
    totalPurchased: 194500,
    lastOrderDate: '21 Oct 2024',
    status: 'Active'
  },
  {
    id: 'SUP-003',
    name: 'Sri Lakshmi Wholesalers',
    category: 'Pulses, Dals & Whole Spices',
    contactPerson: 'N. Venkateshwarlu',
    phone: '+91 97010 44520',
    email: 'srilakshmi.pulses@rediffmail.com',
    pendingOrders: 0,
    totalPurchased: 162000,
    lastOrderDate: '15 Oct 2024',
    status: 'Active'
  },
  {
    id: 'SUP-004',
    name: 'Amul Co-op Depot',
    category: 'Fresh Dairy, Butter & Milk',
    contactPerson: 'S. Patel',
    phone: '+91 99890 55123',
    email: 'secunderabad.amul@coop.org',
    pendingOrders: 0,
    totalPurchased: 98000,
    lastOrderDate: '23 Oct 2024',
    status: 'Active'
  },
  {
    id: 'SUP-005',
    name: 'Nestlé & Britannia Agency',
    category: 'Packaged Foods, Biscuits & Noodles',
    contactPerson: 'G. V. Subbarao',
    phone: '+91 98495 66789',
    email: 'hyd.agencies@fmcgdist.com',
    pendingOrders: 0,
    totalPurchased: 112000,
    lastOrderDate: '19 Oct 2024',
    status: 'Active'
  },
  {
    id: 'SUP-006',
    name: 'HUL & Reckitt Agency',
    category: 'Soaps, Detergents & Home Care',
    contactPerson: 'Prashant Joshi',
    phone: '+91 94900 33812',
    email: 'joshi.distributors@hul.in',
    pendingOrders: 0,
    totalPurchased: 135000,
    lastOrderDate: '16 Oct 2024',
    status: 'Active'
  }
];

exports.customersData = [
  {
    id: 'CUST-001',
    name: 'Ramesh Kumar (Teacher)',
    phone: '+91 98492 44102',
    type: 'Regular (Khata)',
    ordersCount: 42,
    totalSpend: 38450,
    khataBalance: 1450,
    lastPurchase: 'Today, 10:20 AM',
    favoriteCategory: 'Grains & Dairy',
    aiInsight: 'Purchases Sona Masoori Rice & Atta every 10-14 days. Clears Khata around the 5th of each month.'
  },
  {
    id: 'CUST-002',
    name: 'Ananya Reddy',
    phone: '+91 99891 22340',
    type: 'Regular',
    ordersCount: 38,
    totalSpend: 29800,
    khataBalance: 0,
    lastPurchase: 'Today, 09:15 AM',
    favoriteCategory: 'Dairy & Packaged Food',
    aiInsight: 'Daily morning walk-in for Amul Milk and bread. High willingness to try new dairy snacks.'
  },
  {
    id: 'CUST-003',
    name: 'Suresh Gupta',
    phone: '+91 94403 77819',
    type: 'Regular (Khata)',
    ordersCount: 56,
    totalSpend: 54200,
    khataBalance: 2800,
    lastPurchase: 'Yesterday, 07:45 PM',
    favoriteCategory: 'Edible Oils & Spices',
    aiInsight: 'Buys 5L Fortune Oil and bulk spices bi-weekly. Outstanding balance exceeds safety threshold.'
  },
  {
    id: 'CUST-004',
    name: 'Dr. Venkat Rao',
    phone: '+91 97005 33418',
    type: 'VIP Regular',
    ordersCount: 29,
    totalSpend: 31200,
    khataBalance: 0,
    lastPurchase: 'Yesterday, 06:10 PM',
    favoriteCategory: 'Organic & Staples',
    aiInsight: 'Always pays via UPI. Prefers premium whole grain Atta and Tata Salt.'
  },
  {
    id: 'CUST-005',
    name: 'Priya Sharma',
    phone: '+91 98488 99120',
    type: 'Walk-in',
    ordersCount: 14,
    totalSpend: 11400,
    khataBalance: 0,
    lastPurchase: '22 Oct 2024',
    favoriteCategory: 'Snacks & Home Care',
    aiInsight: 'Weekend shopper. Frequently purchases biscuits, tea, and dishwashing bars.'
  },
  {
    id: 'CUST-006',
    name: 'Mohammed Irfan (Biryani Point)',
    phone: '+91 99660 77145',
    type: 'Commercial Bulk',
    ordersCount: 68,
    totalSpend: 124800,
    khataBalance: 4500,
    lastPurchase: 'Today, 11:45 AM',
    favoriteCategory: 'Bulk Rice & Spices',
    aiInsight: 'High-volume rice and whole spices buyer. Generates ₹12,000+ monthly revenue.'
  }
];

exports.transactionsData = [
  {
    id: 'ORD-9402',
    time: 'Today, 11:45 AM',
    customer: 'Mohammed Irfan (Biryani Point)',
    customerId: 'CUST-006',
    itemsCount: 4,
    itemsSummary: 'Sona Masoori Rice (25kg x 2), Garam Masala (x 4)',
    amount: 3076,
    paymentMethod: 'Khata / Ledger',
    status: 'Completed'
  },
  {
    id: 'ORD-9401',
    time: 'Today, 10:20 AM',
    customer: 'Ramesh Kumar (Teacher)',
    customerId: 'CUST-001',
    itemsCount: 3,
    itemsSummary: 'Aashirvaad Atta 10kg, Amul Butter 500g, Tata Salt',
    amount: 768,
    paymentMethod: 'UPI (Google Pay)',
    status: 'Completed'
  },
  {
    id: 'ORD-9400',
    time: 'Today, 09:15 AM',
    customer: 'Ananya Reddy',
    customerId: 'CUST-002',
    itemsCount: 2,
    itemsSummary: 'Amul Taaza Milk 1L (x 2), Parle-G Family Pack',
    amount: 233,
    paymentMethod: 'UPI (PhonePe)',
    status: 'Completed'
  },
  {
    id: 'ORD-9399',
    time: 'Today, 08:40 AM',
    customer: 'Walk-in Customer',
    itemsCount: 1,
    itemsSummary: 'Taj Mahal Tea 500g',
    amount: 360,
    paymentMethod: 'Cash',
    status: 'Completed'
  },
  {
    id: 'ORD-9398',
    time: 'Today, 08:15 AM',
    customer: 'Walk-in Customer',
    itemsCount: 3,
    itemsSummary: 'Fortune Sunlite Oil 1L, Toor Dal 1kg',
    amount: 317,
    paymentMethod: 'Cash',
    status: 'Completed'
  }
];

exports.notificationsData = [
  {
    id: 'NOTIF-001',
    category: 'Inventory',
    severity: 'urgent',
    title: 'Rice stock critical',
    message: 'Sona Masoori Rice is at 18 kg (Safety threshold: 30 kg). Stockout risk in 2 days.',
    time: '10 mins ago',
    read: false,
    action: 'open_ai_restock',
    target: 'PROD-001'
  },
  {
    id: 'NOTIF-002',
    category: 'AI Insights',
    severity: 'info',
    title: 'Weekly Demand Surge detected',
    message: 'Rice and Cooking Oil demand up by +21% and +18% due to upcoming festive weekend.',
    time: '1 hour ago',
    read: false,
    action: 'open_insights',
    target: null
  },
  {
    id: 'NOTIF-003',
    category: 'Sales',
    severity: 'success',
    title: 'Daily sales milestone reached',
    message: "Today's revenue crossed ₹18,000 before noon (+12.4% vs same time yesterday).",
    time: '2 hours ago',
    read: true,
    action: 'open_sales',
    target: null
  },
  {
    id: 'NOTIF-004',
    category: 'Orders',
    severity: 'warning',
    title: 'Pending Purchase Order confirmation',
    message: 'Balaji Trading Co confirmed dispatch of Edible Oil shipment for tomorrow morning.',
    time: 'Yesterday',
    read: true,
    action: 'open_suppliers',
    target: 'SUP-002'
  }
];
